<?php

use Illuminate\Database\Seeder;

class TablaEspecialidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $especialidades =[[ 'especialidad' =>  "ABOGACIA" ],
[ 'especialidad' =>  "ADMINISTRACION AGROPECUARIA" ],
[ 'especialidad' =>  "ADMINISTRACION DE EMPRESAS" ],
[ 'especialidad' =>  "ADMINISTRACION DE EMPRESAS DE SERVICIOS" ],
[ 'especialidad' =>  "AGRONOMIA" ],
[ 'especialidad' =>  "ANALISIS DE SISTEMAS" ],
[ 'especialidad' =>  "ARCHIVOLOGIA" ],
[ 'especialidad' =>  "ARQUITECTURA" ],
[ 'especialidad' =>  "ARTES APLICADAS" ],
[ 'especialidad' =>  "ARTES PLASTICAS" ],
[ 'especialidad' =>  "ASISTENCIA GERENCIAL (SECRETARIADO)" ],
[ 'especialidad' =>  "ASTRONOMIA" ],
[ 'especialidad' =>  "ATENCION TEMPRANA E INTEGRACION SOCIO-EDUCATIVA" ],
[ 'especialidad' =>  "BIBLIOTECOLOGIA" ],
[ 'especialidad' =>  "BIOQUIMICA" ],
[ 'especialidad' =>  "BROMATOLOGIA" ],
[ 'especialidad' =>  "CALIGRAFO PUBLICO" ],
[ 'especialidad' =>  "CERAMICA" ],
[ 'especialidad' =>  "CIENCIA POLITICAS" ],
[ 'especialidad' =>  "CIENCIAS BIOLOGICAS" ],
[ 'especialidad' =>  "CIENCIAS DE LA EDUCACION" ],
[ 'especialidad' =>  "CLASIFICACION DE GRANOS" ],
[ 'especialidad' =>  "COMERCIO ELECTRONICO" ],
[ 'especialidad' =>  "COMERCIO INTERNACIONAL/ADUANA" ],
[ 'especialidad' =>  "COMUNICACION SOCIAL" ],
[ 'especialidad' =>  "CONTADOR PUBLICO" ],
[ 'especialidad' =>  "CORRECCION LITERARIA" ],
[ 'especialidad' =>  "COSMOBIOLOGIA Y ASTROLOGIAÂ Â " ],
[ 'especialidad' =>  "CRIMINALISTICA" ],
[ 'especialidad' =>  "DANZA" ],
[ 'especialidad' =>  "DIAGNOSTICO POR IMAGENES" ],
[ 'especialidad' =>  "DIGITAL" ],
[ 'especialidad' =>  "ECONOMIA" ],
[ 'especialidad' =>  "EDUCACION DEPORTIVA Y RECREACION" ],
[ 'especialidad' =>  "EDUCACION ESPECIAL" ],
[ 'especialidad' =>  "EDUCACION FISICA" ],
[ 'especialidad' =>  "EDUCACION INICIAL" ],
[ 'especialidad' =>  "EMERGENCIAS MEDICAS" ],
[ 'especialidad' =>  "ENFERMERIA" ],
[ 'especialidad' =>  "ESCRIBANIA/NOTARIAL" ],
[ 'especialidad' =>  "FARMACIA" ],
[ 'especialidad' =>  "FILOSOFIA" ],
[ 'especialidad' =>  "FINANZAS" ],
[ 'especialidad' =>  "FISICA" ],
[ 'especialidad' =>  "FONOAUDIOLOGIA" ],
[ 'especialidad' =>  "FOTOGRAFIA" ],
[ 'especialidad' =>  "FRANCES" ],
[ 'especialidad' =>  "FRANCESA" ],
[ 'especialidad' =>  "GASTRONOMIA" ],
[ 'especialidad' =>  "GEOGRAFIA" ],
[ 'especialidad' =>  "GEOLOGIA" ],
[ 'especialidad' =>  "GERENCIAMIENTO/MANAGEMENT" ],
[ 'especialidad' =>  "GESTION AMBIENTAL" ],
[ 'especialidad' =>  "GESTION CULTURA" ],
[ 'especialidad' =>  "GRAFICO" ],
[ 'especialidad' =>  "GRAFOLOGO PUBLICO" ],
[ 'especialidad' =>  "HIGIENE Y SEGURIDAD EN EL TRABAJO" ],
[ 'especialidad' =>  "HISTORIA" ],
[ 'especialidad' =>  "HOTELERIA" ],
[ 'especialidad' =>  "INDUSTRIAL" ],
[ 'especialidad' =>  "INFORMATICA" ],
[ 'especialidad' =>  "INGENIERIA AERONAUTICA" ],
[ 'especialidad' =>  "INGENIERIA BIOMEDICA" ],
[ 'especialidad' =>  "INGENIERIA CIVIL" ],
[ 'especialidad' =>  "INGENIERIA ELECTRICA" ],
[ 'especialidad' =>  "INGENIERIA ELECTRONICA" ],
[ 'especialidad' =>  "INGENIERIA EN AGRIMENSURA" ],
[ 'especialidad' =>  "INGENIERIA EN COMPUTACION" ],
[ 'especialidad' =>  "INGENIERIA EN SISTEMAS DE INFORMACION" ],
[ 'especialidad' =>  "INGENIERIA EN TELECOMUNICACIONES" ],
[ 'especialidad' =>  "INGENIERIA INDUSTRIAL" ],
[ 'especialidad' =>  "INGENIERIA MECANICA" ],
[ 'especialidad' =>  "INGENIERIA METALURGICA" ],
[ 'especialidad' =>  "INGENIERIA QUIMICA" ],
[ 'especialidad' =>  "INSTRUMENTACION QUIRURGICA" ],
[ 'especialidad' =>  "INTERIORES" ],
[ 'especialidad' =>  "KINESIOLOGIA Y FISIOTERAPIA" ],
[ 'especialidad' =>  "LABORATORIO DE ANALISIS" ],
[ 'especialidad' =>  "LENGUA ESPAÑOLA" ],
[ 'especialidad' =>  "LENGUAS ABORIGENES" ],
[ 'especialidad' =>  "LITERATURA" ],
[ 'especialidad' =>  "LOCUCION" ],
[ 'especialidad' =>  "LOGISTICA" ],
[ 'especialidad' =>  "MARKETING/COMERCIALIZACION" ],
[ 'especialidad' =>  "MARTILLERO Y CORREDOR PUBLICO" ],
[ 'especialidad' =>  "MATEMATICA" ],
[ 'especialidad' =>  "MEDICINA" ],
[ 'especialidad' =>  "MICROBIOLOGIA" ],
[ 'especialidad' =>  "MODA" ],
[ 'especialidad' =>  "MUSEOLOGIA" ],
[ 'especialidad' =>  "MUSICA" ],
[ 'especialidad' =>  "NUTRICION" ],
[ 'especialidad' =>  "ODONTOLOGIA" ],
[ 'especialidad' =>  "OPTICA Y CONTACTOLOGIA" ],
[ 'especialidad' =>  "OTROS" ],
[ 'especialidad' =>  "PERIODISMO" ],
[ 'especialidad' =>  "PLASTICA Y TEATRO)" ],
[ 'especialidad' =>  "PODOLOGIA" ],
[ 'especialidad' =>  "PRODUCCION Y TECNOLOGIA DE ALIMENTOS" ],
[ 'especialidad' =>  "PRODUCTOR - ASESOR DE SEGUROS" ],
[ 'especialidad' =>  "PROFESORADO DE IDIOMAS" ],
[ 'especialidad' =>  "PROFESORADO DEL 1Âº Y 2Âº CICLO DE LA EGB (ENSEÑANZA PRIMARIA)" ],
[ 'especialidad' =>  "PROFESORADO EN BIOLOGIA" ],
[ 'especialidad' =>  "PROFESORADO EN CIENCIAS DE LA COMPUTACION" ],
[ 'especialidad' =>  "PROFESORADO EN CIENCIAS SAGRADAS" ],
[ 'especialidad' =>  "PROFESORADO EN CIENCIAS SOCIALES Y JURIDICAS" ],
[ 'especialidad' =>  "PROFESORADO EN ECONOMIA" ],
[ 'especialidad' =>  "PROFESORADO EN FILOSOFIA" ],
[ 'especialidad' =>  "PROFESORADO EN FISICA" ],
[ 'especialidad' =>  "PROFESORADO EN GEOGRAFIA" ],
[ 'especialidad' =>  "PROFESORADO EN HISTORIA" ],
[ 'especialidad' =>  "PROFESORADO EN LENGUA" ],
[ 'especialidad' =>  "PROFESORADO EN LITERATURA" ],
[ 'especialidad' =>  "PROFESORADO EN MATEMATICA" ],
[ 'especialidad' =>  "PROFESORADO EN PSICOLOGIA" ],
[ 'especialidad' =>  "PROFESORADO EN QUIMICA" ],
[ 'especialidad' =>  "PROFESORADO EN TECNOLOGIA" ],
[ 'especialidad' =>  "PROTESIS DENTAL" ],
[ 'especialidad' =>  "PSICOLOGIA" ],
[ 'especialidad' =>  "PSICOMOTRICIDAD" ],
[ 'especialidad' =>  "PSICOPEDAGOGIA" ],
[ 'especialidad' =>  "PUBLICIDAD" ],
[ 'especialidad' =>  "QUIMICA" ],
[ 'especialidad' =>  "RECURSOS HUMANOS" ],
[ 'especialidad' =>  "RELACIONES INTERNACIONALES" ],
[ 'especialidad' =>  "RRPP E INSTITUCIONALES" ],
[ 'especialidad' =>  "SECUNDARIO" ],
[ 'especialidad' =>  "SOCIOLOGIA" ],
[ 'especialidad' =>  "SOCIOPEDAGOGIA" ],
[ 'especialidad' =>  "TEATRO" ],
[ 'especialidad' =>  "TELEVISION Y VIDEO" ],
[ 'especialidad' =>  "TERAPIA OCUPACIONAL" ],
[ 'especialidad' =>  "TERAPIAS NATURALES" ],
[ 'especialidad' =>  "TITERES" ],
[ 'especialidad' =>  "TRABAJO SOCIAL" ],
[ 'especialidad' =>  "TURISMO" ],
[ 'especialidad' =>  "VETERINARIA" ],
[ 'especialidad' =>  "WEB Y REDES INFORMATICAS" ],];

DB::table('especialidades')->insert($especialidades);
    }
}
